### ISSUE TITLE
Example Java Client doesn't build

### ISSUE THREAD

**Issue by sappling** [eclipse/tahu#145] opened 2021-08-31 01:19 UTC
Following [the instructions ](https://docs.chariot.io/display/CLD79/B:+Example+Java+Client)for building the java client results in the error: 
Could not resolve dependencies for project org.eclipse.tahu.example:sparkplug_b_example:jar:0.5.12: Could not find artifact org.eclipse.tahu:tahu-java:jar:0.5.12 in central

It appears that you don't have your client library published to maven central, but your examples depend on this.  It would be much easier to use this if you published your library publicly and if the example would build.

**Comment by wes-johnson** [comment] 2022-01-25 01:45
Closing as duplicate of #87

**Closed by wes-johnson** 2022-01-25 01:45 UTC
