### ISSUE TITLE
Maven Central Artifact?

### ISSUE THREAD

**Issue by mgagliardo91** [eclipse/tahu#158] opened 2021-12-10 19:23 UTC
I'm a bit confused on how to access the Decoder/Encoder for the SB spec? Is the java library published anywhere that can be accessed publicly?

I see an open issue from over a year ago with the same topic: https://github.com/eclipse/tahu/issues/87

Any reason why this has not been published to `org.eclipse.tahu:tahu-java`?

**Comment by wes-johnson** [comment] 2022-01-25 01:45
Closing as duplicate of #87

**Closed by wes-johnson** 2022-01-25 01:45 UTC
